In [ ]:
!pip install tensorflow scikit-fuzzy scipy numpy ucimlrepo matplotlib seaborn kagglehub

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 920.8/920.8 kB 13.8 MB/s eta 0:00:00


In [51]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [52]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("drgfreeman/rockpaperscissors")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'rockpaperscissors' dataset.
Path to dataset files: /kaggle/input/rockpaperscissors


In [54]:
dataset_path = "/kaggle/input/rockpaperscissors/rps-cv-images"

train_datagen = ImageDataGenerator(rescale=1./255, validation_split=0.2)

train_generator = train_datagen.flow_from_directory(dataset_path, target_size=(150, 150), batch_size=32, class_mode='categorical', subset='training',)

validation_generator = train_datagen.flow_from_directory(dataset_path, target_size=(150, 150), batch_size=32, class_mode='categorical', subset='validation',)



Found 1751 images belonging to 3 classes.
Found 437 images belonging to 3 classes.


Let's inspect the classes identified by the `ImageDataGenerator`.

In [56]:
model = Sequential([
  Conv2D(32, (3,3), activation= 'relu', input_shape = (150,150,3)),
  MaxPooling2D(2,2),
  Conv2D(64, (3,3), activation= 'relu'),
  MaxPooling2D(2,2),
  Conv2D(128, (3,3), activation= 'relu'),
  MaxPooling2D(2,2),
  Flatten(),
  Dense(512,activation= 'relu'),
  Dense(3, activation= 'softmax')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [57]:
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_24 (Conv2D)              │ (None, 148, 148, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_24 (MaxPooling2D) │ (None, 74, 74, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_25 (Conv2D)              │ (None, 72, 72, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_25 (MaxPooling2D) │ (None, 36, 36, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_26 (Conv2D)              │ (None, 34, 34, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_26 (MaxPooling2D) │ (None, 17, 17, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_8 (Flatten)             │ (None, 36992)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 512)            │    18,940,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 3)              │         1,539 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 19,035,203 (72.61 MB)

 Trainable params: 19,035,203 (72.61 MB)

 Non-trainable params: 0 (0.00 B)

In [58]:
model.compile(
loss='categorical_crossentropy',
optimizer='adam',
metrics=['accuracy'])

In [59]:
history = model.fit(
  train_generator,
  validation_data=validation_generator,
  epochs=10
)

Epoch 1/10
55/55 ━━━━━━━━━━━━━━━━━━━━ 115s 2s/step - accuracy: 0.6511 - loss: 0.8384 - val_accuracy: 0.8284 - val_loss: 0.4378
Epoch 2/10
55/55 ━━━━━━━━━━━━━━━━━━━━ 111s 2s/step - accuracy: 0.9183 - loss: 0.2569 - val_accuracy: 0.9359 - val_loss: 0.1867
Epoch 3/10
55/55 ━━━━━━━━━━━━━━━━━━━━ 109s 2s/step - accuracy: 0.9566 - loss: 0.1408 - val_accuracy: 0.9542 - val_loss: 0.1406
Epoch 4/10
55/55 ━━━━━━━━━━━━━━━━━━━━ 110s 2s/step - accuracy: 0.9680 - loss: 0.0911 - val_accuracy: 0.9405 - val_loss: 0.1569
Epoch 5/10
55/55 ━━━━━━━━━━━━━━━━━━━━ 112s 2s/step - accuracy: 0.9777 - loss: 0.0625 - val_accuracy: 0.9497 - val_loss: 0.1464
Epoch 6/10
55/55 ━━━━━━━━━━━━━━━━━━━━ 110s 2s/step - accuracy: 0.9852 - loss: 0.0430 - val_accuracy: 0.9634 - val_loss: 0.1127
Epoch 7/10
55/55 ━━━━━━━━━━━━━━━━━━━━ 109s 2s/step - accuracy: 0.9909 - loss: 0.0240 - val_accuracy: 0.9634 - val_loss: 0.2018
Epoch 8/10
55/55 ━━━━━━━━━━━━━━━━━━━━ 106s 2s/step - accuracy: 0.9943 - loss: 0.0277 - val_accuracy: 0.9703 - v

In [60]:
val_loss, val_acc = model.evaluate(validation_generator)
print(f'Validation loss: {val_loss}, Validation accuracy: {val_acc}')


14/14 ━━━━━━━━━━━━━━━━━━━━ 6s 437ms/step - accuracy: 0.9703 - loss: 0.1055
Validation loss: 0.10554607212543488, Validation accuracy: 0.970251739025116


In [61]:
predictions = model.predict(validation_generator)
print(predictions) # Output berupa probabilitas prediksi tiap kelas

14/14 ━━━━━━━━━━━━━━━━━━━━ 8s 502ms/step
[[8.3752972e-01 1.4420669e-01 1.8263556e-02]
 [6.4592205e-05 9.9993533e-01 3.0312315e-11]
 [4.5979727e-06 1.2550319e-14 9.9999529e-01]
 ...
 [1.8394868e-04 1.1967960e-16 9.9981612e-01]
 [1.5874343e-02 9.2416241e-15 9.8412561e-01]
 [1.0000000e+00 3.4093336e-11 1.2544414e-11]]
